name: Inshorts Autoupdate
on:
  push:
    paths:
      - .github/workflows/scrape.yml # Only run a new workflow every time this file (scrape.yml) file changes
  schedule:
    - cron: '*/5 * * * *' # every 5min
defaults:
  run:
    shell: bash
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
<<<<<<< HEAD
        uses: actions/checkout@v3 # checkout the repository content to github runner.
=======
        uses: actions/checkout@v3
>>>>>>> 6fe89fe (Updated workflow)
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 #install the python needed
          cache: 'pip'
<<<<<<< HEAD
      - run: pip install -r code/requirements.txt
      - name: execute py script # run the run.py to get the latest data
        run: |
=======
      - name: execute py script # run the run.py to get the latest data
        run: |
          pip install beautifulsoup4
          pip install requests
>>>>>>> 6fe89fe (Updated workflow)
          python code/scrape.py
          #git config --global user.name ${{github.actor}} 
          #git config --global user.email ${{github.actor}}@users.noreply.github.com 
          #git add inshorts.json
          #git commit inshorts.json -m "Inshorts updated"
          #git push -f
      - uses: actions/checkout@v3
      - name: Deploy gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: ${{vars.GIST_ID}}
          file_path: inshorts.json
          file_type: binary
