name: Inshorts Autoupdate
on:
  push:
    paths:
      - .github/workflows/scrape.yml # Only run a new workflow every time this file (scrape.yml) file changes
  schedule:
    - cron: '*/5 * * * *' # every 5min
defaults:
  run:
    shell: bash
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'pip'
      - name: execute py script # run the run.py to get the latest data
        run: |
          pip install beautifulsoup4
          pip install requests
          python code/scrape.py
      - name: Deploy gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: ${{vars.GIST_ID}}
          file_path: code/inshorts.json
          file_type: binary
