name: Inshorts Autoupdate
on:
  push:
    paths:
      - .github/workflows/scrape.yml
      - code/scrape.py
  schedule:
    - cron: '*/10 * * * *' # every 10min
defaults:
  run:
    shell: bash
env:
    GH_TOKEN: ${{ secrets.TOKEN }}
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'pip'
      - name: execute py script # run the run.py to get the latest data
        run: |
          pip install beautifulsoup4
          pip install requests
          python code/scrape.py
          gh gist edit ${{vars.GIST_ID}} inshorts.json

